name: CI/CD to Kubernetes

on:
workflow_dispatch
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t juhee24/app-k8s-basic:latest .

    - name: Push Docker image
      run: |
        docker push juhee24/app-k8s-basic:latest

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f app-k8s-basic-deployment.yaml
        kubectl apply -f app-k8s-basic-service.yaml
